name: NSPB Canon Wiki (Archive)
baseurl: /nspb-wiki-archive

description: Archive of the NSPB Canon Wiki, formerly hosted on Miraheze

collections:
  wiki:
    output: true

auto-relative: true

plugins:
  - jekyll-postcss

postcss:
  cache: false
