name: NSPB Canon Wiki (Archive)

description: Archive of the NSPB Canon Wiki, formerly hosted on Miraheze

collections:
  wiki:
    output: true


plugins:
  - jekyll-postcss

postcss:
  cache: false
